import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MyThemeContextProvider } from "./store/myThemeContext";
import Header from "./components/Header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MyThemeContextProvider>
        <body className={inter.className}>
          {/* <Header /> */}
          {children}
        </body>
      </MyThemeContextProvider>
    </html>
  );
}
